  
version: '3.4'
services:
  gmaas-github-api:
    image: gmaas2/github-api:latest
    build:
      dockerfile: Dockerfile
      context: app/
    ports:
      - 5000:5000
    environment:
      GITHUB_API_LOG_LEVEL: "DEBUG"
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics"
      prometheus.io/port: "5000"
    networks: 
      - gmaas-github-api_network   
  prometheus:
    image: prom/prometheus:v2.22.0
    depends_on:
      - gmaas-github-api
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
      - gmaas-github-api_network
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.3.3
    ports: 
      - "3000:3000"
    depends_on:
      - prometheus
    networks: 
      - gmaas-github-api_network  
  alert-manager:
    image: prom/alertmanager:v0.21.0
    ports: 
      - 9093:9093
    depends_on:
      - prometheus
    networks: 
      - gmaas-github-api_network
networks: 
  gmaas-github-api_network:
    driver: bridge