apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-github-api
  namespace: default
  labels:
    app: poc-github-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-github-api
  template:
    metadata:
      name: poc-github-api
      labels:
        app: poc-github-api
    spec:
      containers:
      - name: poc-github-api
        image: gmaas2/sre-uol-github-api:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        -  name: http
           containerPort: 5000
