apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poc-github-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poc-github-api
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50