{{- if eq .Values.ingressNginx.enabled true }}
{{- if (lookup "v1" "Service" "ingress-nginx" "ingress-nginx-controller")}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: {{ .rewriteTarget }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingressNginx.pathUrl }}
        pathType: {{ .Values.ingressNginx.pathType }}
        backend:
          service:
            name: {{ .Release.Name }}
            port: 
              number: {{ .Values.ingressNginx.portNumber }}
{{- end }}
{{- end }}