apiVersion: v1
kind: Service
metadata:
  name: github_api
  namespace: default
  labels:
    app: github_api
spec:
  selector:
    app: github_api
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
