apiVersion: v1
kind: Service
metadata:
  name: poc-github-api
  namespace: default
  labels:
    app: poc-github-api
spec:
  selector:
    app: poc-github-api
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
