container:
  replicas: 3
  imagePullPolicy: Always
  livenessProbe:
    enabled: true
    httpGet:
      path: /health
      port: 5000
      scheme: HTTP
    timeoutSeconds: 3
    failureThreshold: 3
    periodSeconds: 60 #Esse tempo de 60 seg é por conta do Rate Limit da API do Github. A ideia é não bloquear o acesso.
    successThreshold: 1
    initialDelaySeconds: 5      
  readinessProbe:
    enabled: true
    httpGet:
      path: /read
      port: 5000
      scheme: HTTP
    timeoutSeconds: 3
    failureThreshold: 3
    periodSeconds: 300
    successThreshold: 1
    initialDelaySeconds: 5
  ports:
  - name: http
    containerPort: 5000
  resources:
    enabled: true
    limits:
      memory: "64Mi"
      cpu: "50m"    

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  averageUtilization: 50

configmap:
  enabled: true
  GITHUB_API_LOG_LEVEL: DEBUG

ingressNginx:
  rewriteTarget: /
  pathUrl: /githubapi
  pathType: Prefix
  portNumber: 5000

service:
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000